name: C++

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "tests/cpp/**"
      - ".github/workflows/cpp.yaml"

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install wget clang-tidy libarmadillo-dev r-cran-rcpparmadillo
          wget https://github.com/tnagler/RcppThread/archive/refs/tags/v2.1.2.tar.gz
          sudo tar -xf v2.1.2.tar.gz -C /

      - name: Lint
        working-directory: src/
        run: |
          clang-tidy *.cpp -header-filter="^.*/src/.*" --use-color -- -I/usr/lib/R/site-library/RcppArmadillo/include -I/usr/lib/R/site-library/Rcpp/include -I/usr/share/R/include -I/RcppThread-2.1.2/inst/include
  testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install g++ clang

      - name: Run tests
        working-directory: tests/cpp
        run: |
          cmake . && make 
          ./tests --success